export const ROUTES = {
  login: '/login',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  dashboard: '/dashboard',
  customers: '/customers',
  riders: '/riders',
  deliveries: '/deliveries',
  orders: '/orders',
  stores: '/stores',
  categories: '/categories',
  liveTracking: '/live-tracking',
  reports: '/reports',
  pricing: '/pricing',
  settings: '/settings',
}
